apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      name: streamlit-app
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-ts-ml
          image: "us.icr.io/ml-api/streamlit-ts-ml:0.2.0"
          ports:
            - containerPort: 5051
          resources:
            limits:
              cpu: 0.3
              memory: 512M
          env:
            - name: DEBUG_MODE
              value: "1"
      imagePullSecrets:
        - name: default-icr-io